### ISSUE TITLE
Consolidate SpringTo and ConfigureSpring

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion-starmap#63] opened 2016-10-08 16:18 UTC
The Starmap still has [`springTo` and `configureSpring` as separate plans](https://material-motion.gitbooks.io/material-motion-starmap/content/specifications/motion_family/springs.html).  Based on our conversations this week, we should consolidate them.

Does configuration need to be it's own property?

``` javascript
springTo(
  {
    destination: {x: 100},
    speed: 5,
    bounciness: 100,
  }
)
```

seems a bit nicer/more intuitive than

``` javascript
springTo(
  {
    destination: {x: 100},
    configuration: {
      speed: 5,
      bounciness: 100,
    }
  }
)
```

**Comment by pingpongboss** [comment] 2016-10-08 18:03
Main advantage of having configuration be its own property is
1. null configuration means "don't change" - it's harder to make primitive properties "nullable"
2. easy to enforce that speed and bounciness must both be if a configuration is to be provided.

**Comment by appsforartists** [comment] 2016-10-09 16:49
Sounds like #61

**Comment by jverkoey** [comment] 2016-11-07 22:45
Dupe of https://github.com/material-motion/starmap/issues/67

**Closed as completed by jverkoey** 2016-11-07 22:45 UTC

**Comment by jverkoey** [comment] 2016-11-07 22:47
We'll likely keep the Configuration object in the spec so that the configuration can easily be stored and reused across multiple SpringTo instances.
